// Hand-written in the same shape `flutterfire configure` generates.
// Normally auto-generated by the FlutterFire CLI, but the CLI's logged-in
// account here doesn't have access to the gdgdeployordie Firebase project
// (it was created under a different Google account) — so this was built
// manually from the Web app config (Firebase Console > Project Settings >
// General > Web app) and android/app/google-services.json.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for web and android in this project.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VBuHw8stf7u_2-Z1iJXeaE3nW2-tcuQ',
    authDomain: 'gdgdeployordie.firebaseapp.com',
    projectId: 'gdgdeployordie',
    storageBucket: 'gdgdeployordie.firebasestorage.app',
    messagingSenderId: '398185915394',
    appId: '1:398185915394:web:f424cb1697639ba74eb31b',
    measurementId: 'G-D31KYGSWRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0OT69lRslvr_R-_eKYWussxeczGwQ-e4',
    appId: '1:398185915394:android:2dc8a74dc01cd7474eb31b',
    messagingSenderId: '398185915394',
    projectId: 'gdgdeployordie',
    storageBucket: 'gdgdeployordie.firebasestorage.app',
  );
}
