/**
 * Digital receipt emails on approval — deliberately plain code, not an LLM
 * skill, same reasoning as server/services/payroll.ts: formatting a record's
 * already-structured fields into an HTML email is not a task that benefits
 * from a language model, and using one would just add latency, cost, and a
 * new failure mode for no benefit.
 *
 * Non-blocking by design (same pattern as Storage image uploads): a failed
 * email should never fail the approval itself. Approval is the core,
 * audited action; the email is a convenience layer on top of it.
 */

const SENDGRID_ENDPOINT = "https://api.sendgrid.com/v3/mail/send";

export class EmailError extends Error {}

interface RegisterFieldConfig {
  key: string;
  label: string;
}

export interface ApprovedRecordForReceipt {
  id: string;
  registerType: string;
  fields: Record<string, string | number | null>;
  approvedAt: number;
}

function formatReceiptHtml(record: ApprovedRecordForReceipt, typeLabel: string, fieldDefs: RegisterFieldConfig[]): string {
  const rows = fieldDefs
    .map((def) => {
      const value = record.fields[def.key];
      return `<tr><td style="padding:4px 12px 4px 0;color:#666;">${def.label}</td><td style="padding:4px 0;font-weight:600;">${value ?? "—"}</td></tr>`;
    })
    .join("");

  const approvedDate = new Date(record.approvedAt).toLocaleString();

  return `
    <div style="font-family:sans-serif;max-width:480px;margin:0 auto;">
      <h2 style="margin-bottom:4px;">Digital Receipt — ${typeLabel}</h2>
      <p style="color:#666;font-size:13px;margin-top:0;">Approved ${approvedDate} · Record ID ${record.id}</p>
      <table style="border-collapse:collapse;width:100%;margin-top:16px;">${rows}</table>
      <p style="color:#999;font-size:11px;margin-top:24px;">Automatically generated by Slip Flow on approval. This is a digital backup copy, not a substitute for the original record.</p>
    </div>
  `.trim();
}

export async function sendReceiptEmail(
  record: ApprovedRecordForReceipt,
  typeLabel: string,
  fieldDefs: RegisterFieldConfig[]
): Promise<void> {
  const apiKey = process.env.SENDGRID_API_KEY;
  const sender = process.env.RECEIPT_SENDER_EMAIL;
  const recipient = process.env.RECEIPT_RECIPIENT_EMAIL;

  if (!apiKey || !sender || !recipient) {
    throw new EmailError("SENDGRID_API_KEY, RECEIPT_SENDER_EMAIL, and RECEIPT_RECIPIENT_EMAIL must all be set");
  }

  const html = formatReceiptHtml(record, typeLabel, fieldDefs);

  const res = await fetch(SENDGRID_ENDPOINT, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      personalizations: [{ to: [{ email: recipient }] }],
      from: { email: sender },
      subject: `Digital Receipt — ${typeLabel} — ${new Date(record.approvedAt).toLocaleDateString()}`,
      content: [{ type: "text/html", value: html }],
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new EmailError(`SendGrid request failed (${res.status}): ${body}`);
  }
}
